// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkyngddkrssxeqodtuse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJreW5nZGRrcnNzeGVxb2R0dXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyOTk5NjksImV4cCI6MjA1ODg3NTk2OX0.VTDcztLwgK28-etKnK3mtDGz5kaH8IzlKN9W6-zsnEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);